using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ShramSetu.Core.Entities;

namespace ShramSetu.Services;

public interface IPdfService
{
    byte[] GeneratePayslip(PayrollRecord record);
    byte[] GenerateWorkContract(WorkContract contract);
    byte[] GenerateWorkerCv(Worker worker, IEnumerable<Review> reviews, IEnumerable<WorkerBadge> badges);
}

public class PdfService : IPdfService
{
    public byte[] GeneratePayslip(PayrollRecord record)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11));
                page.Header().Element(ComposeHeader);
                page.Content().Element(c => ComposePayslipContent(c, record));
                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by ShramSetu    ").FontColor(Colors.Grey.Medium);
                    x.Span(DateTime.Now.ToString("dd MMM yyyy HH:mm")).FontColor(Colors.Grey.Medium);
                });
            });
        }).GeneratePdf();
    }

    public byte[] GenerateWorkContract(WorkContract contract)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(50);
                page.DefaultTextStyle(x => x.FontSize(11));
                page.Header().Element(ComposeHeader);
                page.Content().Element(c => ComposeContractContent(c, contract));
                page.Footer().AlignCenter().Text(x =>
                    x.Span("This is a digitally generated contract by ShramSetu").FontColor(Colors.Grey.Medium));
            });
        }).GeneratePdf();
    }

    public byte[] GenerateWorkerCv(Worker worker, IEnumerable<Review> reviews, IEnumerable<WorkerBadge> badges)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Element(ComposeHeader);
                page.Content().Element(c => ComposeCvContent(c, worker, reviews, badges));
                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by ShramSetu    ").FontColor(Colors.Grey.Medium);
                    x.Span(DateTime.Now.ToString("dd MMM yyyy")).FontColor(Colors.Grey.Medium);
                });
            });
        }).GeneratePdf();
    }

    // ?? Shared Header ????????????????????????????????????????????????????????

    private static void ComposeHeader(IContainer container)
    {
        container.Row(row =>
        {
            row.RelativeItem().Column(col =>
            {
                col.Item().Text("ShramSetu").FontSize(22).Bold().FontColor(Colors.Blue.Darken2);
                col.Item().Text("Connecting Workers with Opportunity").FontSize(10).FontColor(Colors.Grey.Medium);
            });
            row.ConstantItem(100).AlignRight().Text("OFFICIAL").Bold().FontColor(Colors.Blue.Medium);
        });
    }

    // ?? Payslip Content ???????????????????????????????????????????????????????

    private static void ComposePayslipContent(IContainer container, PayrollRecord r)
    {
        container.Column(col =>
        {
            col.Item().PaddingVertical(10).Text("PAYSLIP").FontSize(18).Bold().AlignCenter();
            col.Item().LineHorizontal(1).LineColor(Colors.Blue.Medium);
            col.Item().PaddingVertical(8);

            col.Item().Table(table =>
            {
                table.ColumnsDefinition(c => { c.RelativeColumn(); c.RelativeColumn(); });
                table.Cell().Text("Worker Name").Bold();  table.Cell().Text(r.Worker?.FullName ?? "");
                table.Cell().Text("Employer").Bold();     table.Cell().Text(r.Employer?.Name ?? "");
                table.Cell().Text("Period").Bold();       table.Cell().Text($"{r.PeriodStart:dd MMM yyyy}  {r.PeriodEnd:dd MMM yyyy}");
                table.Cell().Text("Days Worked").Bold();  table.Cell().Text(r.DaysWorked.ToString());
                table.Cell().Text("Daily Wage").Bold();   table.Cell().Text($"₹{r.DailyWage:N2}");
                table.Cell().Text("Gross Amount").Bold(); table.Cell().Text($"₹{r.GrossAmount:N2}");
                table.Cell().Text("Deductions").Bold();   table.Cell().Text($"₹{r.Deductions:N2}");
                table.Cell().Text("Net Payable").Bold().FontColor(Colors.Green.Darken2);
                table.Cell().Text($"₹{r.NetAmount:N2}").Bold().FontColor(Colors.Green.Darken2);
                table.Cell().Text("Status").Bold();       table.Cell().Text(r.Status.ToString());
                if (r.PaidAt.HasValue)
                {
                    table.Cell().Text("Paid On").Bold();
                    table.Cell().Text(r.PaidAt.Value.ToString("dd MMM yyyy"));
                }
            });
        });
    }

    // ?? Contract Content ??????????????????????????????????????????????????????

    private static void ComposeContractContent(IContainer container, WorkContract c)
    {
        container.Column(col =>
        {
            col.Item().PaddingVertical(10).Text("WORK AGREEMENT").FontSize(18).Bold().AlignCenter();
            col.Item().LineHorizontal(1).LineColor(Colors.Blue.Medium);
            col.Item().PaddingVertical(8);
            if (c.Content is not null) col.Item().Text(c.Content);

            col.Item().PaddingTop(20).Row(row =>
            {
                row.RelativeItem().Column(sig =>
                {
                    sig.Item().Text("Worker Signature").Bold();
                    sig.Item().Text(c.WorkerSignedAt.HasValue
                        ? $"Signed on {c.WorkerSignedAt:dd MMM yyyy}"
                        : "Not yet signed").FontColor(Colors.Grey.Medium);
                });
                row.RelativeItem().Column(sig =>
                {
                    sig.Item().Text("Employer Signature").Bold();
                    sig.Item().Text(c.EmployerSignedAt.HasValue
                        ? $"Signed on {c.EmployerSignedAt:dd MMM yyyy}"
                        : "Not yet signed").FontColor(Colors.Grey.Medium);
                });
            });
        });
    }

    // ?? Worker CV Content ?????????????????????????????????????????????????????

    private static void ComposeCvContent(IContainer container, Worker worker,
        IEnumerable<Review> reviews, IEnumerable<WorkerBadge> badges)
    {
        var reviewList  = reviews.ToList();
        var badgeList   = badges.ToList();
        var avgRating   = reviewList.Any() ? reviewList.Average(r => r.Rating) : 0;
        var stars       = new string('?', (int)Math.Round(avgRating)) + new string('?', 5 - (int)Math.Round(avgRating));

        container.Column(col =>
        {
            col.Item().PaddingVertical(10).Text("WORKER PROFILE / CV").FontSize(18).Bold().AlignCenter();
            col.Item().LineHorizontal(2).LineColor(Colors.Blue.Medium);
            col.Item().PaddingVertical(10);

            // Personal details
            col.Item().Table(table =>
            {
                table.ColumnsDefinition(c => { c.RelativeColumn(); c.RelativeColumn(2); });
                void Row(string label, string value) { table.Cell().Text(label).Bold(); table.Cell().Text(value); }
                Row("Full Name",    worker.FullName);
                Row("Phone",        worker.Phone);
                Row("Skill",        worker.SkillCategory?.Name ?? "");
                Row("Experience",   $"{worker.YearsOfExperience} year(s)");
                Row("Location",     $"{worker.LocationCity}, {worker.LocationState}");
                Row("Daily Wage",   $"₹{worker.ExpectedDailyWage:N0}");
                Row("KYC Status",   worker.KycStatus.ToString());
                Row("Availability", worker.IsAvailable ? "Available" : "Not Available");
            });

            // Badges
            if (badgeList.Any())
            {
                col.Item().PaddingTop(12).Text("Badges & Certifications").Bold().FontSize(13);
                col.Item().PaddingTop(4).Text(string.Join("  |  ", badgeList.Select(b => $"? {b.Tier}")))
                   .FontColor(Colors.Green.Darken2);
            }

            // Rating
            col.Item().PaddingTop(12).Text("Employer Rating").Bold().FontSize(13);
            col.Item().PaddingTop(4).Text(reviewList.Any()
                ? $"{stars}  {avgRating:F1}/5.0  ({reviewList.Count} review(s))"
                : "No reviews yet").FontColor(Colors.Orange.Medium);

            // Sub-skills
            if (!string.IsNullOrWhiteSpace(worker.SubSkills))
            {
                col.Item().PaddingTop(12).Text("Sub-Skills").Bold().FontSize(13);
                col.Item().PaddingTop(4).Text(worker.SubSkills);
            }

            col.Item().PaddingTop(20).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
            col.Item().PaddingTop(8).Text("This profile has been verified and generated by ShramSetu.")
               .FontColor(Colors.Grey.Medium).FontSize(9).AlignCenter();
        });
    }
}


